#!/bin/sh -ex
BRANCH=$(git rev-parse --abbrev-ref HEAD)
update_branch
[ "$1" ] && PR=$1 || read PR
if [ "$PR" -eq "$PR" ] 2>/dev/null; then
    git fetch origin pull/$PR/head
    LOCAL_BRANCH=FETCH_HEAD
else
    LOCAL_BRANCH=$PR
fi
git merge --no-ff --log -S -m "Merging pull request $PR" $LOCAL_BRANCH
#git push origin $BRANCH
